services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"  # Changed the host port to 3307
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql-data: